PUT http://localhost:3001/api/persons/5ed526045d1e644c88c0f3a3
Content-Type: application/json

{
    "name": "test", 
    "number": "mod number", 
    "id": 2759551, 
    "date": "2020-06-01T22:44:38.388Z"
}